# Generated by Django 3.2.8 on 2022-02-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='shortDescription',
            field=models.CharField(default='A short description', max_length=3000),
            preserve_default=False,
        ),
    ]
