# Generated by Django 4.0.2 on 2022-02-14 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelttry', '0004_alter_profile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='whatsApp',
            field=models.CharField(default='+2349063435621', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2349063435621'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsApp',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2349063435621'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
